### ISSUE TITLE
Не работает автообновление в docker

### ISSUE THREAD

**Issue by ncrmnt** [ElizarovEugene/TorrentMonitor#211]
Не работает автоматическое обновление тем/раздач. При этом если запустить обновление из UI или внутри контейнера командой `php -q /data/htdocs/engine.php` то всё обновляется.

Запускаю контейнер со следующим конфигом
```yaml
version: '3'

services:
  torrentmonitor:
    container_name: torrentmonitor
    image: alfonder/torrentmonitor:latest
    restart: unless-stopped
    ports:
      - 8794:80
    volumes:
      - ./data/torrents:/data/htdocs/torrents
      - ./data/db:/data/htdocs/db
      - ./data/logs:/data/htdocs/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGUD=1000
      - PHP_TIMEZONE="Europe/Moscow"
      - CRON_TIMEOUT="*/5 * * * *"
```
Пробовал добавить CRON_COMMAND="php -q /data/htdocs/engine.php" без результатов
